### ISSUE TITLE
 Add Dark Mode

### ISSUE THREAD

**Issue by KauaLimaMartins** [AbnerLago/PetPaws#3]
# Hello Abner
 
I found your project very interesting and would like to help by putting a **Dark mode** on it, what do you think?

**Comment by AbnerLago** [comment]
That's such a great idea! 
But, for now, I am starting this project and I don't have any finished page yet. Anyways, I would love to have you as a partner in this development!

**Comment by KauaLimaMartins** [comment]
Great, so I can help you with login, registration, adding pets etc. just tell me i run to perform!

**Comment by AbnerLago** [comment]
Deal! You can contact me at abnerabrahao6@gmail.com.
